### ISSUE TITLE
Image uploads in Issues and Wiki don't display

### ISSUE THREAD

**Issue by keybits** [dwrensha/gitlab-sandstorm#11]
![image](https://cloud.githubusercontent.com/assets/809823/10725574/dd645802-7bc4-11e5-879a-9bfe2735e227.png)

The link that is generated when uploading an image is of the form:

`![P1060458](http://should-use-relative-url-here:10000/gitlab/repo/uploads/951c29aab3e7d12e67b78060f6ed4699/P1060458.JPG)`

**Comment by dwrensha** [comment]
Thanks for reporting this.

As you might be able to tell from the link text, the problem here is that GitLab is trying to use a statically-configured absolute URL for the image. That's not going to work because Sandstorm [serves every session from a fresh unguessable host](https://docs.sandstorm.io/en/latest/using/security-practices/#client-sandboxing). So we'll need to find where in the source code GitLab is generating these links and convert them to relative URLs instead.

**Comment by dwrensha** [comment]
Fixed in the verison that I published just now: https://apps.sandstorm.io/app/zx9d3pt0fjh4uqrprjftgpqfwgzp6y2ena6098ug3ctv37uv6kfh
