### ISSUE TITLE
Issues not visible when sharing access in Sandstorm for Work

### ISSUE THREAD

**Issue by germakoci** [dwrensha/gitlab-sandstorm#18]
I'm using a gitlab grain on sandstorm for work, share it with others and the issues are not visible to any other user (no matter if master, reporter or guest).

**Comment by dwrensha** [comment]
Ouch. I can reproduce this problem. I'm not sure what's going wrong. The grain owner can see issues but apparently nobody else can, unless they navigate directly there (e.g. /gitlab/repo/issues/1 ).

Thanks for the report!

**Comment by dwrensha** [comment]
Current guess: somehow all issues are defaulting to being "confidential".

**Comment by germakoci** [comment]
thanks @dwrensha - I guess this goes only for the grain owner, right? since I have issues shared by one of the collaborators to the grain, and I can see them. 

btw, is there a place to change these settings ?

**Comment by dwrensha** [comment]
OK, I've published a new release that should fix this problem. You can download the new version from the [app market](https://apps.sandstorm.io/app/zx9d3pt0fjh4uqrprjftgpqfwgzp6y2ena6098ug3ctv37uv6kfh) or just wait a day to auto-upgrade.

The fix is [here](https://github.com/dwrensha/gitlabhq/commit/328bf322b8a28b24d52fdc47d2fa93ce4f658c7b). The problem had to do with the fact that we're using SQLite, while upstream only officially supports Postgres and MySql.

> btw, is there a place to change these settings ?

In a "public" gitlab repo, there is a checkbox in the "new issue" form that allows you to make the issue confidential. Since repos in the Sandstorm port are always "private", this checkbox does not show up.

**Comment by germakoci** [comment]
oau, that was fast, thanks! have the new version, it works. 

> The problem had to do with the fact that we're using SQLite, while upstream only officially supports Postgres and MySql.

I get it: I heard that before, I guess it was for PaperWork inside sandstorm
