### ISSUE TITLE
Gitlab repos available via https, is ssh possible? 

### ISSUE THREAD

**Issue by cbrulak** [dwrensha/gitlab-sandstorm#27]
I have my sandstorm instance protected by oauth via google sign (only my personal domain can access). When I create a new gitlab repo though I see the following: 
* i can only access the repo (on command line) via https
* there is no authentication on the repo. 

Is this by design or did I miss something? 

Thanks

**Comment by ocdtrekkie** [comment]
When you say "there is no authentication on the repo", is there not an API key as part of the URL?

**Comment by cbrulak** [comment]
Actually, now i see there is. I misread the output from gitlab. For example:
 
echo url=https://XXX:YYYY@api-ID.NAME.sandcats.io/gitlab/repo.git | git -c credential.helper=store credential approve
 git clone -c credential.helper=store https://XXX@api-ID.NAME.sandcats.io/gitlab/repo.git repo_ayhbymae_RENAME_ME


But, is it possible to use ssh keys?

**Comment by ocdtrekkie** [comment]
Not currently, no. Sandstorm knows how to talk in HTTP APIs. Bear in mind that GitLab does not handle the authentication here, Sandstorm does. (Which is why GitLab vulnerabilities are extremely unlikely to impact the security of a Sandstorm-hosted instance.

In order to support other forms of access and authentication, Sandstorm's capabilities would need to be extended to support that type of communication. Or the app would need direct IP access, and to handle authentication itself.

**Comment by cbrulak** [comment]
I see,thanks.
