### ISSUE TITLE
webhook

### ISSUE THREAD

**Issue by ghost** [dwrensha/gitlab-sandstorm#9]
Not quite sure if the webhook functionality of gitlab still available while it runs at sandstorm? Was trying gitlab via sandstorm platform, but seems it doesn't offer this .. :cry:

**Comment by dwrensha** [comment]
Webhooks are currently not enabled in the Sandstorm package because they require the app to make external network requests from the server. See https://blog.sandstorm.io/news/2015-06-10-network-access-permission-android-vs-sandstorm.html. I think we need to wait until the powerbox UI is ready before enabling this feature.

**Comment by ghost** [comment]
ok, look forward to it.
